-- ============================================================================
-- CICLOPAG V5 - GRUPOS, USUARIOS, PERMISSOES, CONVITES E ANEXOS
-- Execute este arquivo INTEIRO no Supabase SQL Editor depois das versões V2-V4.
-- O script é idempotente: pode ser executado novamente.
-- ============================================================================

begin;

create extension if not exists pgcrypto;

-- --------------------------------------------------------------------------
-- Grupos de usuários e permissões por módulo
-- --------------------------------------------------------------------------
create table if not exists public.grupos_usuarios (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nome text not null check (char_length(trim(nome)) between 2 and 80),
  descricao text,
  sistema boolean not null default false,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, nome)
);

create table if not exists public.grupo_permissoes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  grupo_id uuid not null references public.grupos_usuarios(id) on delete cascade,
  modulo text not null,
  visualizar boolean not null default false,
  cadastrar boolean not null default false,
  editar boolean not null default false,
  excluir boolean not null default false,
  imprimir boolean not null default false,
  emitir boolean not null default false,
  criado_em timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (grupo_id, modulo)
);

alter table public.membros_empresa
  add column if not exists grupo_usuario_id uuid references public.grupos_usuarios(id) on delete set null;

create index if not exists idx_grupos_usuarios_empresa on public.grupos_usuarios(empresa_id, ativo, nome);
create index if not exists idx_grupo_permissoes_grupo on public.grupo_permissoes(grupo_id, modulo);
create index if not exists idx_membros_grupo_usuario on public.membros_empresa(grupo_usuario_id);

-- --------------------------------------------------------------------------
-- Convites de acesso. O usuário cria a própria senha no Supabase Auth e o
-- convite o vincula automaticamente à empresa e ao grupo selecionado.
-- --------------------------------------------------------------------------
create table if not exists public.convites_acesso (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  funcionario_registro_id uuid,
  nome text not null,
  email text not null,
  grupo_usuario_id uuid not null references public.grupos_usuarios(id) on delete restrict,
  token text not null unique,
  status text not null default 'pendente' check (status in ('pendente','aceito','cancelado','expirado')),
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  expira_em timestamptz not null default (now() + interval '7 days'),
  aceito_em timestamptz,
  updated_at timestamptz not null default now(),
  unique (empresa_id, email)
);

create index if not exists idx_convites_empresa_status on public.convites_acesso(empresa_id, status, criado_em desc);
create index if not exists idx_convites_token on public.convites_acesso(token);

-- Histórico das ações operacionais que dependem de integrações ou mudança de estado.
create table if not exists public.acoes_erp (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  registro_id uuid,
  modulo text not null,
  acao text not null,
  detalhes jsonb not null default '{}'::jsonb,
  executado_por uuid references auth.users(id) on delete set null,
  executado_em timestamptz not null default now()
);
create index if not exists idx_acoes_erp_empresa on public.acoes_erp(empresa_id, executado_em desc);

-- --------------------------------------------------------------------------
-- Updated_at
-- --------------------------------------------------------------------------
drop trigger if exists trg_grupos_usuarios_updated_at on public.grupos_usuarios;
create trigger trg_grupos_usuarios_updated_at before update on public.grupos_usuarios
for each row execute function public.definir_updated_at();

drop trigger if exists trg_grupo_permissoes_updated_at on public.grupo_permissoes;
create trigger trg_grupo_permissoes_updated_at before update on public.grupo_permissoes
for each row execute function public.definir_updated_at();

drop trigger if exists trg_convites_acesso_updated_at on public.convites_acesso;
create trigger trg_convites_acesso_updated_at before update on public.convites_acesso
for each row execute function public.definir_updated_at();

-- --------------------------------------------------------------------------
-- Catálogo oficial de módulos usado para gerar as permissões.
-- --------------------------------------------------------------------------
create table if not exists public.catalogo_modulos_erp (
  modulo text primary key,
  titulo text not null,
  secao text not null,
  ordem integer not null default 0
);

insert into public.catalogo_modulos_erp (modulo,titulo,secao,ordem) values
('clientes','Clientes','Cadastros',10),('fornecedores','Fornecedores','Cadastros',20),('funcionarios','Funcionários','Cadastros',30),('transportadoras','Transportadoras','Cadastros',40),('cadastros-opcoes','Opções auxiliares','Cadastros',50),
('produtos','Produtos','Itens',60),('servicos','Serviços','Itens',70),('grades-variacoes','Grades e variações','Itens',80),('itens-opcoes','Opções auxiliares de itens','Itens',90),
('orcamentos-produtos','Orçamentos de produtos','Orçamentos',100),('orcamentos-servicos','Orçamentos de serviços','Orçamentos',110),('orcamentos-opcoes','Opções auxiliares de orçamentos','Orçamentos',120),
('vendas-produtos','Vendas de produtos','Vendas',130),('vendas-servicos','Vendas de serviços','Vendas',140),('vendas-balcao','PDV e caixa','Vendas',150),('vendas-devolucoes','Trocas e devoluções','Vendas',160),('vendas-opcoes','Opções auxiliares de vendas','Vendas',170),
('os-gerenciar','Ordens de serviço','Ordens de serviços',180),('os-painel','Painel de O.S.','Ordens de serviços',190),('os-opcoes','Opções auxiliares de O.S.','Ordens de serviços',200),
('estoque-movimentacoes','Movimentações','Estoque',210),('estoque-ajustes','Ajustes','Estoque',220),('estoque-transferencias','Transferências','Estoque',230),('estoque-cotacoes','Cotações','Estoque',240),('compras-produtos','Compras de produtos','Estoque',250),('compras-servicos','Compras de serviços','Estoque',260),('estoque-opcoes','Opções auxiliares de estoque','Estoque',270),
('contas-pagar','Contas a pagar','Financeiro',280),('contas-receber','Contas a receber','Financeiro',290),('contas-bancarias','Contas bancárias','Financeiro',300),('formas-pagamento','Formas de pagamento','Financeiro',310),('dre','DRE gerencial','Financeiro',320),('fluxo-caixa','Fluxo de caixa','Financeiro',330),('boletos','Boletos bancários','Financeiro',340),('financeiro-opcoes','Opções auxiliares financeiras','Financeiro',350),
('notas-produtos','Notas de produtos','Fiscal',360),('notas-servicos','Notas de serviços','Fiscal',370),('notas-consumidor','Notas do consumidor','Fiscal',380),('notas-compras','Notas de compras','Fiscal',390),('importacao-dados','Importação de dados','Fiscal',400),('fiscal-opcoes','Opções auxiliares fiscais','Fiscal',410),
('contratos-servicos','Contratos de serviços','Contratos',420),('contratos-locacoes','Contratos de locação','Contratos',430),('contratos-assinaturas','Assinaturas recorrentes','Contratos',440),('contratos-opcoes','Opções auxiliares de contratos','Contratos',450),
('atendimentos','Atendimentos','Atendimentos',460),('agenda','Agenda','Agenda',470),('area-cliente','Área do Cliente','Área do Cliente',480),('relatorios','Relatórios','Relatórios',490),
('integracoes','Integrações e aplicativos','Aplicativos',500),('contabilidade','Área da Contabilidade','Aplicativos',510),('loja-virtual','Loja Virtual','Aplicativos',520),
('config-gerais','Configurações gerais','Configurações',530),('meu-plano','Meu plano','Configurações',540),('usuarios','Usuários','Configurações',550),('grupos-usuarios','Grupos de usuários','Configurações',560),('dados-empresa','Dados da empresa','Configurações',570),('marca-empresa','Marca da empresa','Configurações',580),('empresas-lojas','Empresas / Lojas','Configurações',590),('certificado-digital','Certificado digital','Configurações',600),('modelos-email','Modelos de e-mails','Configurações',610),('avisos-email','Avisos por e-mail','Configurações',620)
on conflict (modulo) do update set titulo=excluded.titulo, secao=excluded.secao, ordem=excluded.ordem;

-- --------------------------------------------------------------------------
-- Cria grupos padrão para uma empresa e preenche permissões.
-- --------------------------------------------------------------------------
create or replace function public.criar_grupos_padrao_empresa(p_empresa_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_admin uuid;
  v_vendedor uuid;
begin
  insert into public.grupos_usuarios (empresa_id,nome,descricao,sistema,ativo)
  values (p_empresa_id,'Administração','Acesso administrativo completo.',true,true)
  on conflict (empresa_id,nome) do update set sistema=true, ativo=true
  returning id into v_admin;

  insert into public.grupos_usuarios (empresa_id,nome,descricao,sistema,ativo)
  values (p_empresa_id,'Vendedor','Acesso comercial a clientes, orçamentos, vendas, O.S., atendimentos e agenda.',true,true)
  on conflict (empresa_id,nome) do update set sistema=true, ativo=true
  returning id into v_vendedor;

  insert into public.grupo_permissoes (empresa_id,grupo_id,modulo,visualizar,cadastrar,editar,excluir,imprimir,emitir)
  select p_empresa_id,v_admin,c.modulo,true,true,true,true,true,true
  from public.catalogo_modulos_erp c
  on conflict (grupo_id,modulo) do update set visualizar=true,cadastrar=true,editar=true,excluir=true,imprimir=true,emitir=true;

  insert into public.grupo_permissoes (empresa_id,grupo_id,modulo,visualizar,cadastrar,editar,excluir,imprimir,emitir)
  select p_empresa_id,v_vendedor,c.modulo,
    c.modulo in ('clientes','orcamentos-produtos','orcamentos-servicos','vendas-produtos','vendas-servicos','vendas-balcao','vendas-devolucoes','os-gerenciar','os-painel','atendimentos','agenda','produtos','servicos'),
    c.modulo in ('clientes','orcamentos-produtos','orcamentos-servicos','vendas-produtos','vendas-servicos','vendas-balcao','vendas-devolucoes','os-gerenciar','atendimentos','agenda'),
    c.modulo in ('clientes','orcamentos-produtos','orcamentos-servicos','vendas-produtos','vendas-servicos','vendas-balcao','os-gerenciar','atendimentos','agenda'),
    false,
    c.modulo in ('clientes','orcamentos-produtos','orcamentos-servicos','vendas-produtos','vendas-servicos','vendas-balcao','os-gerenciar','atendimentos','agenda'),
    false
  from public.catalogo_modulos_erp c
  on conflict (grupo_id,modulo) do nothing;
end;
$$;

revoke all on function public.criar_grupos_padrao_empresa(uuid) from public;
grant execute on function public.criar_grupos_padrao_empresa(uuid) to authenticated;

create or replace function public.trg_criar_grupos_padrao_empresa()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.criar_grupos_padrao_empresa(new.id);
  return new;
end;
$$;

drop trigger if exists on_empresa_criada_grupos on public.empresas;
create trigger on_empresa_criada_grupos after insert on public.empresas
for each row execute function public.trg_criar_grupos_padrao_empresa();

-- Empresas já existentes.
do $$
declare r record;
begin
  for r in select id from public.empresas loop
    perform public.criar_grupos_padrao_empresa(r.id);
  end loop;
end $$;

-- Grupo administrativo automático para proprietários/administradores.
create or replace function public.definir_grupo_padrao_membro()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.grupo_usuario_id is null and new.papel in ('proprietario','administrador') then
    select id into new.grupo_usuario_id
    from public.grupos_usuarios
    where empresa_id=new.empresa_id and nome='Administração'
    limit 1;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_membros_grupo_padrao on public.membros_empresa;
create trigger trg_membros_grupo_padrao before insert or update of papel,grupo_usuario_id on public.membros_empresa
for each row execute function public.definir_grupo_padrao_membro();

update public.membros_empresa m
set grupo_usuario_id=g.id
from public.grupos_usuarios g
where m.empresa_id=g.empresa_id and g.nome='Administração' and m.papel in ('proprietario','administrador') and m.grupo_usuario_id is null;

-- --------------------------------------------------------------------------
-- Função central de autorização. Proprietário/administrador sempre passam.
-- Demais usuários dependem da permissão do grupo.
-- --------------------------------------------------------------------------
create or replace function public.usuario_pode(p_empresa_id uuid,p_modulo text,p_acao text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.membros_empresa m
    left join public.grupo_permissoes gp
      on gp.grupo_id=m.grupo_usuario_id and gp.empresa_id=m.empresa_id and gp.modulo=p_modulo
    where m.empresa_id=p_empresa_id
      and m.usuario_id=(select auth.uid())
      and m.ativo
      and (
        m.papel in ('proprietario','administrador')
        or case p_acao
          when 'visualizar' then coalesce(gp.visualizar,false)
          when 'cadastrar' then coalesce(gp.cadastrar,false)
          when 'editar' then coalesce(gp.editar,false)
          when 'excluir' then coalesce(gp.excluir,false)
          when 'imprimir' then coalesce(gp.imprimir,false)
          when 'emitir' then coalesce(gp.emitir,false)
          else false
        end
      )
  );
$$;

revoke all on function public.usuario_pode(uuid,text,text) from public;
grant execute on function public.usuario_pode(uuid,text,text) to authenticated;

create or replace function public.minhas_permissoes(p_empresa_id uuid)
returns table(modulo text,visualizar boolean,cadastrar boolean,editar boolean,excluir boolean,imprimir boolean,emitir boolean)
language sql
stable
security definer
set search_path = ''
as $$
  select c.modulo,
    case when m.papel in ('proprietario','administrador') then true else coalesce(gp.visualizar,false) end,
    case when m.papel in ('proprietario','administrador') then true else coalesce(gp.cadastrar,false) end,
    case when m.papel in ('proprietario','administrador') then true else coalesce(gp.editar,false) end,
    case when m.papel in ('proprietario','administrador') then true else coalesce(gp.excluir,false) end,
    case when m.papel in ('proprietario','administrador') then true else coalesce(gp.imprimir,false) end,
    case when m.papel in ('proprietario','administrador') then true else coalesce(gp.emitir,false) end
  from public.membros_empresa m
  cross join public.catalogo_modulos_erp c
  left join public.grupo_permissoes gp on gp.grupo_id=m.grupo_usuario_id and gp.modulo=c.modulo
  where m.empresa_id=p_empresa_id and m.usuario_id=(select auth.uid()) and m.ativo
  order by c.ordem;
$$;

revoke all on function public.minhas_permissoes(uuid) from public;
grant execute on function public.minhas_permissoes(uuid) to authenticated;

-- --------------------------------------------------------------------------
-- Convites: consulta segura e aceite pelo próprio e-mail autenticado.
-- --------------------------------------------------------------------------
create or replace function public.consultar_convite_acesso(p_token text)
returns table(email text,nome text,empresa_nome text,grupo_nome text,expira_em timestamptz)
language sql
stable
security definer
set search_path = ''
as $$
  select c.email,c.nome,e.nome,g.nome,c.expira_em
  from public.convites_acesso c
  join public.empresas e on e.id=c.empresa_id
  join public.grupos_usuarios g on g.id=c.grupo_usuario_id
  where c.token=p_token and c.status='pendente' and c.expira_em>now()
  limit 1;
$$;

revoke all on function public.consultar_convite_acesso(text) from public;
grant execute on function public.consultar_convite_acesso(text) to anon,authenticated;

create or replace function public.aceitar_convite_acesso(p_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_email text;
  v_invite public.convites_acesso%rowtype;
  v_member uuid;
begin
  if v_user is null then raise exception 'Usuário não autenticado'; end if;
  select lower(email) into v_email from auth.users where id=v_user;
  select * into v_invite from public.convites_acesso where token=p_token and status='pendente' and expira_em>now() for update;
  if not found then raise exception 'Convite inválido ou expirado'; end if;
  if lower(v_invite.email)<>v_email then raise exception 'O e-mail autenticado não corresponde ao convite'; end if;

  insert into public.membros_empresa (empresa_id,usuario_id,papel,grupo_usuario_id,ativo)
  values (v_invite.empresa_id,v_user,'leitura',v_invite.grupo_usuario_id,true)
  on conflict (empresa_id,usuario_id) do update set grupo_usuario_id=excluded.grupo_usuario_id,ativo=true
  returning id into v_member;

  update public.convites_acesso set status='aceito',aceito_em=now() where id=v_invite.id;
  return v_member;
end;
$$;

revoke all on function public.aceitar_convite_acesso(text) from public;
grant execute on function public.aceitar_convite_acesso(text) to authenticated;

-- Lista segura de usuários da empresa, incluindo perfil e grupo.
create or replace function public.listar_usuarios_empresa(p_empresa_id uuid)
returns table(id uuid,usuario_id uuid,nome text,email text,papel text,ativo boolean,grupo_usuario_id uuid,grupo_nome text)
language sql
stable
security definer
set search_path = ''
as $$
  select m.id,m.usuario_id,coalesce(p.nome,'Usuário'),coalesce(p.email,''),m.papel,m.ativo,m.grupo_usuario_id,g.nome
  from public.membros_empresa m
  left join public.perfis p on p.id=m.usuario_id
  left join public.grupos_usuarios g on g.id=m.grupo_usuario_id
  where m.empresa_id=p_empresa_id
    and public.usuario_pode(p_empresa_id,'usuarios','visualizar')
  order by coalesce(p.nome,p.email);
$$;

revoke all on function public.listar_usuarios_empresa(uuid) from public;
grant execute on function public.listar_usuarios_empresa(uuid) to authenticated;

-- --------------------------------------------------------------------------
-- RLS
-- --------------------------------------------------------------------------
alter table public.grupos_usuarios enable row level security;
alter table public.grupo_permissoes enable row level security;
alter table public.convites_acesso enable row level security;
alter table public.acoes_erp enable row level security;
alter table public.catalogo_modulos_erp enable row level security;

-- Limpa políticas desta versão.
do $$
declare p record;
begin
  for p in select schemaname,tablename,policyname from pg_policies
    where schemaname='public' and tablename in ('grupos_usuarios','grupo_permissoes','convites_acesso','acoes_erp','catalogo_modulos_erp')
  loop execute format('drop policy if exists %I on %I.%I',p.policyname,p.schemaname,p.tablename); end loop;
end $$;

create policy catalogo_modulos_ler on public.catalogo_modulos_erp for select to authenticated using (true);

create policy grupos_ver on public.grupos_usuarios for select to authenticated
using (public.usuario_e_membro(empresa_id));
create policy grupos_inserir on public.grupos_usuarios for insert to authenticated
with check (public.usuario_pode(empresa_id,'grupos-usuarios','cadastrar'));
create policy grupos_editar on public.grupos_usuarios for update to authenticated
using (public.usuario_pode(empresa_id,'grupos-usuarios','editar'))
with check (public.usuario_pode(empresa_id,'grupos-usuarios','editar'));
create policy grupos_excluir on public.grupos_usuarios for delete to authenticated
using (not sistema and public.usuario_pode(empresa_id,'grupos-usuarios','excluir'));

create policy permissoes_ver on public.grupo_permissoes for select to authenticated
using (public.usuario_e_membro(empresa_id));
create policy permissoes_gerenciar on public.grupo_permissoes for all to authenticated
using (public.usuario_pode(empresa_id,'grupos-usuarios','editar'))
with check (public.usuario_pode(empresa_id,'grupos-usuarios','editar'));

create policy convites_ver on public.convites_acesso for select to authenticated
using (public.usuario_pode(empresa_id,'usuarios','visualizar'));
create policy convites_criar on public.convites_acesso for insert to authenticated
with check (public.usuario_pode(empresa_id,'usuarios','cadastrar') and criado_por=(select auth.uid()));
create policy convites_editar on public.convites_acesso for update to authenticated
using (public.usuario_pode(empresa_id,'usuarios','editar'))
with check (public.usuario_pode(empresa_id,'usuarios','editar'));
create policy convites_excluir on public.convites_acesso for delete to authenticated
using (public.usuario_pode(empresa_id,'usuarios','excluir'));

create policy acoes_ver on public.acoes_erp for select to authenticated
using (public.usuario_e_membro(empresa_id));
create policy acoes_inserir on public.acoes_erp for insert to authenticated
with check (public.usuario_e_membro(empresa_id) and executado_por=(select auth.uid()));

-- Usuários: o próprio usuário enxerga seu vínculo; a lista completa exige permissão.
drop policy if exists membros_ver_mesma_empresa on public.membros_empresa;
create policy membros_ver_mesma_empresa on public.membros_empresa for select to authenticated
using (usuario_id=(select auth.uid()) or public.usuario_pode(empresa_id,'usuarios','visualizar'));

-- Administrador também pode gerenciar membros, além do proprietário.
drop policy if exists membros_inserir_gestores on public.membros_empresa;
drop policy if exists membros_editar_gestores on public.membros_empresa;
drop policy if exists membros_excluir_gestores on public.membros_empresa;
create policy membros_inserir_gestores on public.membros_empresa for insert to authenticated
with check (public.usuario_pode(empresa_id,'usuarios','cadastrar'));
create policy membros_editar_gestores on public.membros_empresa for update to authenticated
using (public.usuario_pode(empresa_id,'usuarios','editar'))
with check (public.usuario_pode(empresa_id,'usuarios','editar'));
create policy membros_excluir_gestores on public.membros_empresa for delete to authenticated
using (public.usuario_pode(empresa_id,'usuarios','excluir') and usuario_id<>(select auth.uid()));

-- Perfis de colegas visíveis apenas para quem pode visualizar usuários.
drop policy if exists perfis_ver_colegas_autorizados on public.perfis;
create policy perfis_ver_colegas_autorizados on public.perfis for select to authenticated
using (
  id=(select auth.uid()) or exists (
    select 1 from public.membros_empresa alvo
    where alvo.usuario_id=perfis.id and alvo.ativo and public.usuario_pode(alvo.empresa_id,'usuarios','visualizar')
  )
);

-- Permissões reais nos registros operacionais.
drop policy if exists registros_erp_ver_membro on public.registros_erp;
drop policy if exists registros_erp_inserir_equipe on public.registros_erp;
drop policy if exists registros_erp_editar_equipe on public.registros_erp;
drop policy if exists registros_erp_excluir_gestores on public.registros_erp;
create policy registros_erp_ver_permissao on public.registros_erp for select to authenticated
using (public.usuario_pode(empresa_id,modulo,'visualizar'));
create policy registros_erp_inserir_permissao on public.registros_erp for insert to authenticated
with check (public.usuario_pode(empresa_id,modulo,'cadastrar') and criado_por=(select auth.uid()));
create policy registros_erp_editar_permissao on public.registros_erp for update to authenticated
using (public.usuario_pode(empresa_id,modulo,'editar'))
with check (public.usuario_pode(empresa_id,modulo,'editar'));
create policy registros_erp_excluir_permissao on public.registros_erp for delete to authenticated
using (public.usuario_pode(empresa_id,modulo,'excluir'));

-- Clientes têm tabela própria, mas obedecem ao mesmo grupo.
drop policy if exists clientes_ver_membro on public.clientes;
drop policy if exists clientes_inserir_equipe on public.clientes;
drop policy if exists clientes_editar_equipe on public.clientes;
drop policy if exists clientes_excluir_gestores on public.clientes;
create policy clientes_ver_permissao on public.clientes for select to authenticated
using (public.usuario_pode(empresa_id,'clientes','visualizar'));
create policy clientes_inserir_permissao on public.clientes for insert to authenticated
with check (public.usuario_pode(empresa_id,'clientes','cadastrar'));
create policy clientes_editar_permissao on public.clientes for update to authenticated
using (public.usuario_pode(empresa_id,'clientes','editar'))
with check (public.usuario_pode(empresa_id,'clientes','editar'));
create policy clientes_excluir_permissao on public.clientes for delete to authenticated
using (public.usuario_pode(empresa_id,'clientes','excluir'));

-- --------------------------------------------------------------------------
-- Storage privado para fotos, XML, PDFs e anexos de até 5 MB.
-- --------------------------------------------------------------------------
insert into storage.buckets (id,name,public,file_size_limit)
values ('erp-anexos','erp-anexos',false,5242880)
on conflict (id) do update set public=false,file_size_limit=5242880;

drop policy if exists erp_anexos_ler on storage.objects;
drop policy if exists erp_anexos_inserir on storage.objects;
drop policy if exists erp_anexos_editar on storage.objects;
drop policy if exists erp_anexos_excluir on storage.objects;

create policy erp_anexos_ler on storage.objects for select to authenticated
using (
  bucket_id='erp-anexos'
  and split_part(name,'/',1) ~* '^[0-9a-f-]{36}$'
  and public.usuario_pode(split_part(name,'/',1)::uuid,split_part(name,'/',2),'visualizar')
);
create policy erp_anexos_inserir on storage.objects for insert to authenticated
with check (
  bucket_id='erp-anexos'
  and split_part(name,'/',1) ~* '^[0-9a-f-]{36}$'
  and public.usuario_pode(split_part(name,'/',1)::uuid,split_part(name,'/',2),'cadastrar')
);
create policy erp_anexos_editar on storage.objects for update to authenticated
using (bucket_id='erp-anexos' and split_part(name,'/',1) ~* '^[0-9a-f-]{36}$' and public.usuario_pode(split_part(name,'/',1)::uuid,split_part(name,'/',2),'editar'))
with check (bucket_id='erp-anexos' and split_part(name,'/',1) ~* '^[0-9a-f-]{36}$' and public.usuario_pode(split_part(name,'/',1)::uuid,split_part(name,'/',2),'editar'));
create policy erp_anexos_excluir on storage.objects for delete to authenticated
using (bucket_id='erp-anexos' and split_part(name,'/',1) ~* '^[0-9a-f-]{36}$' and public.usuario_pode(split_part(name,'/',1)::uuid,split_part(name,'/',2),'excluir'));

-- Grants explícitos.
grant select on public.catalogo_modulos_erp to authenticated;
grant select,insert,update,delete on public.grupos_usuarios,public.grupo_permissoes,public.convites_acesso,public.acoes_erp to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;

-- Resultado esperado: Success. No rows returned
