-- ============================================================
-- CICLOPAG V4 - BASE OPERACIONAL PADRONIZADA
-- Execute este arquivo inteiro no Supabase SQL Editor.
-- Pode ser executado novamente sem duplicar estruturas.
-- ============================================================

begin;

-- Amplia clientes para armazenar o formulario completo sem perder
-- as colunas principais usadas em buscas e no dashboard.
alter table public.clientes
  add column if not exists tipo text not null default 'Pessoa física';

alter table public.clientes
  add column if not exists dados jsonb not null default '{}'::jsonb;

-- Registros operacionais dos modulos. O JSONB mantém todos os campos
-- dos formularios enquanto as colunas principais permitem listas,
-- pesquisas, indicadores e relatorios rapidos.
create table if not exists public.registros_erp (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  modulo text not null,
  tipo text not null,
  titulo text not null check (char_length(trim(titulo)) between 1 and 180),
  status text not null default 'Ativo',
  valor_total numeric(14,2) not null default 0,
  dados jsonb not null default '{}'::jsonb,
  criado_por uuid references auth.users(id) on delete set null,
  criado_em timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_registros_erp_empresa_modulo
  on public.registros_erp(empresa_id, modulo, criado_em desc);

create index if not exists idx_registros_erp_empresa_status
  on public.registros_erp(empresa_id, status);

create index if not exists idx_registros_erp_titulo
  on public.registros_erp using gin (to_tsvector('simple', titulo));

-- Atualizacao automatica.
drop trigger if exists trg_registros_erp_updated_at on public.registros_erp;
create trigger trg_registros_erp_updated_at
before update on public.registros_erp
for each row execute function public.definir_updated_at();

-- Auditoria automatica.
drop trigger if exists trg_registros_erp_auditoria on public.registros_erp;
create trigger trg_registros_erp_auditoria
after insert or update or delete on public.registros_erp
for each row execute function public.registrar_auditoria_automatica();

-- RLS multiempresa.
alter table public.registros_erp enable row level security;

drop policy if exists registros_erp_ver_membro on public.registros_erp;
drop policy if exists registros_erp_inserir_equipe on public.registros_erp;
drop policy if exists registros_erp_editar_equipe on public.registros_erp;
drop policy if exists registros_erp_excluir_gestores on public.registros_erp;

create policy registros_erp_ver_membro on public.registros_erp
for select to authenticated
using (public.usuario_e_membro(empresa_id));

create policy registros_erp_inserir_equipe on public.registros_erp
for insert to authenticated
with check (
  public.usuario_tem_papel(
    empresa_id,
    array['proprietario','administrador','financeiro','atendente','profissional']
  )
  and criado_por = (select auth.uid())
);

create policy registros_erp_editar_equipe on public.registros_erp
for update to authenticated
using (
  public.usuario_tem_papel(
    empresa_id,
    array['proprietario','administrador','financeiro','atendente','profissional']
  )
)
with check (
  public.usuario_tem_papel(
    empresa_id,
    array['proprietario','administrador','financeiro','atendente','profissional']
  )
);

create policy registros_erp_excluir_gestores on public.registros_erp
for delete to authenticated
using (public.usuario_tem_papel(empresa_id, array['proprietario','administrador']));

revoke all on public.registros_erp from anon;
grant select, insert, update, delete on public.registros_erp to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;

-- Resultado esperado: Success. No rows returned
